<?PHP

/**
 *  ChassisPHP - A PHP framework designed for CMS
 *
 * @package ChassisPHP
 * @author  Roger Creasy <roger@chassisPHP.com>
 */

// Initializes the autoloader generated by composer

    $loader = require 'vendor/autoload.php';
    $loader->register();
    //require 'lib/Framework/Core.php';

    use Symfony\Component\HttpFoundation\Request;
    use Symfony\Component\HttpFoundation\Response;
    use Lib\Framework\Core;
    $request = Request::createFromGlobals();                 

    // Use the Core to bootstrap an app
    $app = new Core();

    $app->map(
        '/', function () {
            return new Response('This is the home page!');
        }
    );
    $app->map('/about', function ()
    {
        return new Response('This is the about page!');
    });
    $app->map('/test', function ()
    {
        return new Response('Roger\'s test page?');
    });
    $response = $app->handle($request);
    $response->send();
